### PR TITLE
[Experimental] - Add Dana pump

### PR DESCRIPTION
**Pull request by avouspierre**
Add dana pump with adding the submodule proposed by https://github.com/bastiaanv/DanaKit  (for Loop). 

Very experimental features to test only. 

Don't forget to update your submodule (git submodule update). 

Simulator Screenshot - iPhone 15 - 2024-05-15 at 19 55 20

### CODE REVIEW

**Comment by LiroyvH** [comment]
I'm gonna try to get my hands on a Dana (probably i) to test this if its fully capable? (Meaning: the integration has the pump fully featured: bolus, temp basal, etc.)

**Comment by avouspierre** [comment]
@LiroyvH  I can not test but in theory, all functions available in Trio with a interaction with a pump should be available with Dana

**Comment by LiroyvH** [comment]
@avouspierre I suppose its unlikely this will insta-merge in to Trio; even in Dev. If I do get my hands on a Dana-RS, could you help me patch in the code to dev on my personal fork so I may test?

@bastiaanv Nice work!! :)

**Comment by marionbarker** [comment]
After checking out this branch, I did need to issue this command:
```
git submodule update
```
This triggered the clone command to bring down:
```
https://github.com/bastiaanv/DanaKit.git
489c310 (HEAD, origin/dev, origin/HEAD, dev) fix: Cleanup state better
```

At this time I was able to `xed .` and build Trio with `Dana` added as a pump option on an SE phone running iOS 17.5.
* DanaRS-v3
* Dana-i

For each option, I went through the steps to start scanning for the pump:
* Setting up screen
* Select insulin type
* Delivery speed
* Scanning

I plan to set up the simulator on my rPi and will report in a separate comment, but I believe this is ready to merge into dev.

**Review by marionbarker — APPROVED** [review]

**Comment by marionbarker** [comment]
I successfully configured a Dana simulator and am running Trio talking to the simulator.

**Comment by avouspierre** [comment]
updated with a experimental label for Dana pump.

**Review by bjornoleh — APPROVED** [review]
Approving and merging this to get the dana feature branch into the nightscout repository. The work will continue there.

**Pull request merged**
