### PR TITLE
Update Browser Build for feat/dana

### PR DESCRIPTION
**Pull request by marionbarker**
To enable feat/dana to build with Browser Build:
* update macos to 15
* update xcode to 16.2
* update Fastlane to 2.225.0
* update DanaKit version to fix plist reference

### CODE REVIEW

**Comment by marionbarker** [comment]
This was tested using loopdocs-tester user ID.
Here is the successful browser build
* https://github.com/loopdocs-tester/Trio/actions/runs/12420560868

**Comment by bastiaanv** [comment]
Should I make a PR to Loop&Learn @marionbarker ?

**Review by dnzxy — APPROVED** [review]

**Comment by marionbarker** [comment]
> Should I make a PR to Loop&Learn @marionbarker ?

I now have it configured so I can update the `dev` and `trio` branch for loopandlearn/DanaKit to match bastiaanv/DanaKit by clicking on the Sync fork button. No PR is required for that part of the puzzle; and the SHA in the two usernames match.

This PR fixes some browser build details and points to the new SHA for DanaKit that fixed the plist problem.

**Review by bjornoleh — APPROVED** [review]
Builds with GH and runs on a phone based on brief testing without access to Dana pumps. LGTM.

**Comment by winni67** [comment]
For me, new to Trio and building with GH, I see no workflow. With iAPS, a workflow for building with GH is shown, but ends with errors.

**Comment by bastiaanv** [comment]
@winni67 have you activated the action for your trio repo?

**Comment by winni67** [comment]
Do you mean the 6 repository secrets? Yes and step 1 to 3 works on xdripswift. Step 1-3 is missing in iAPS. In Trio, there is no workflow shown.

**Comment by bjornoleh** [comment]
@winni67 , I think it would be better to look into this on Discord, I tagged you there ☺️

**Pull request merged**
