### PR TITLE
Amend TDD calculation to respect 24 hours and 14 days

### PR DESCRIPTION
**Pull request by avouspierre**
Modify weighted_average to respect the 24 hours of data and 14 days of total TDD.

### CODE REVIEW

**Comment by dnzxy** [comment]
I‘m genuinely confused. This was brought up as a topic of discussion and is now PR‘d with any further conversation about it or its side effects.

**Comment by avouspierre** [comment]
@dnzxy Sorry if the PR is too quickly. I noted the PR interested more than discussion in GitHub ;-) 

@MikePlante1 : 
- 10 or 14 days : just to be compliant with the TDD algorithm. Perhaps not useful but in this case, it will be better to rename variable and update the documentation if necessary ! 
- 2 hours or 24 hours : I did the mistake to believe each value is the eventual insulin value during 5'... and not the total previous 24h. Thanks! 

I close the PR and update the discussion.

**Comment by dnzxy** [comment]
Oh, please don’t close, let’s just make it a draft for now. You did the work already, let’s not waste it 😊 Is that okay with you? I‘ll re-open and change to draft, if so 🤔

**Comment by JohnKitching** [comment]
I could be wrong but I think I recall Tim Street commenting somewhere that in AAPS they found two hours unsafe.

**Comment by avouspierre** [comment]
> Oh, please don’t close, let’s just make it a draft for now. You did the work already, let’s not waste it 😊 Is that okay with you? I‘ll re-open and change to draft, if so 🤔

Don't worry. it is more the argument of Mike than your remark 😂

**Pull request closed without merging**
