### PR TITLE
[feat/dana] Resync branch with Dev & Update DanaKit

### PR DESCRIPTION
**Pull request by bastiaanv**
changes:
- Add Battery age (will be shown after first battery swap & automatically reset every swap)
- Add views to allow blind cannula &/or reservoir refill (in cases where the pump's display is failing)
- fix missing persistency for `bolus sync` & `auto time sync`
- Resync Trio dev to this branch

### CODE REVIEW

**Comment by marionbarker** [comment]
I am still not able to run this code.

I updated to this branch.
I applied patch from [fix: Syntax fixes](https://github.com/loopandlearn/DanaKit/pull/4#top)
The code builds but then fails on startup with `'/private/var/containers/Bundle/Application/6E68AFB3-0F35-41E8-9389-F97CC060CC9A/FreeAPS.app/Frameworks/DanaKit.framework/DanaKit' (no such file)`

Screenshot 2024-12-08 at 10 41 04 AM

**Comment by bastiaanv** [comment]
@marionbarker I updated the DanaKit submodule and my simulator & real phone are working perfectly
Could you try again?

**Review by marionbarker — DISMISSED** [review]
Test build works as expected.
LGTM

**Comment by marionbarker** [comment]
As I was doing my final checks, I found that Xcode 16.1 is modifying a file when I build.
If I reset to the version at bastiaanv:feat/dana and then build again, the file is modified again.
Can someone look at this?

`	modified:   FreeAPS.xcodeproj/xcshareddata/xcschemes/Trio.xcscheme`

```
Trio % git diff
diff --git a/FreeAPS.xcodeproj/xcshareddata/xcschemes/Trio.xcscheme b/FreeAPS.xcodeproj/xcshareddata/xcschemes/Trio.xcscheme
index e5dcba6e..345784b5 100644
--- a/FreeAPS.xcodeproj/xcshareddata/xcschemes/Trio.xcscheme
+++ b/FreeAPS.xcodeproj/xcshareddata/xcschemes/Trio.xcscheme
@@ -169,7 +169,7 @@
             <BuildableReference
                BuildableIdentifier = "primary"
                BlueprintIdentifier = "3E6007862D0C5D0C00B186D1"
-               BuildableName = "DanaKitPlugin.framework"
+               BuildableName = "DanaKitPlugin.loopplugin"
                BlueprintName = "DanaKitPlugin"
                ReferencedContainer = "container:DanaKit/DanaKit.xcodeproj">
             </BuildableReference>
```

**Review by marionbarker — APPROVED** [review]
LGTM

**Review by dnzxy — APPROVED** [review]
LGTM based on Code Review

**Pull request merged**
