### PR TITLE
Update submodule G7SensorKit: update SHA to LoopKit, no change to code

### PR DESCRIPTION
**Pull request by marionbarker**
Please see [Update Submodules to LoopKit #223](https://github.com/nightscout/Trio/issues/223).

This is one of several expected PR to solve this issue. This one handles G7SensorKit submodule.

The code from the loopandlearn SHA is identical to the code from the LoopKit SHA.

The submodule SHA used for the Trio workspace index should come from LoopKit if at all possible.

### CODE REVIEW

**Review by bjornoleh — APPROVED** [review]
Looks good!

**Review by itsmojo — COMMENTED** [review]
Although I believe that I understand the concept of what's going on with stuff as described in https://github.com/nightscout/Trio/issues/223, I don't feel that I have enough relevant experience in these matters at this time. I think I should defer the approval of PR's like this to others with more experience in such matters.

**Comment by bjornoleh** [comment]
> Although I believe that I understand the concept of what's going on with stuff as described in #223, I don't feel that I have enough relevant experience in these matters at this time. I think I should defer the approval of PR's like this to others with more experience in such matters.

This particular PR is actually quite straightforward, as the `Files changed` view shows:

image

As you can see above, there are no changes to the code in the submodule, only the git reference that is now directed at the LoopKit repository instead of the temporary solution of getting it from the loopandlearn repository.

**Review by dnzxy — APPROVED** [review]
Thanks for updating our submodule dependencies. 

LGTM! 

@bjornoleh feel free to merge.

**Comment by bjornoleh** [comment]
Merging with two approvals.

**Pull request merged**
