### PR TITLE
add manual glucose value visualization to chart and history

### PR DESCRIPTION
**Pull request by mountrcg**
Visualize manual Glucose (finger prick) in Chart and history
| Chart | History |
| -- | -- |
| Simulator Screenshot - Dev 13 mini - 2024-06-24 at 16 57 14 | Simulator Screenshot - Dev 13 mini - 2024-06-24 at 16 57 04 |

### CODE REVIEW

**Comment by dnzxy** [comment]
Thank you for tackling this and bringing this small change to Trio. 

If I may ask, why the `ZStack` and to achieve the white outline, and why the white outline? Wouldn’t this also work? Just asking because I seldom see icons have borders on iOS. 

image

**Comment by mountrcg** [comment]
> If I may ask, why the `ZStack` and to achieve the white outline, and why the white outline? Wouldn’t this also work? Just asking because I seldom see icons have borders on iOS.

fixed!

**Comment by MikePlante1** [comment]
I just merged this into `alpha` to test this on a simulator.

I noticed this PR breaks the display when using "Glucose Simulator" for cgm, but it seems that's probably not really so much a problem with this PR as it is that readings from Glucose Simulator use `nil` for `type` instead of `sgv`.

**Comment by marionbarker** [comment]
## Summary
Success using NS as a CGM
Switched to CGM simulator and it continued to work - not sure of the configuration that @MikePlante1 referred to.

### Test
Began with SE running Trio, alpha branch, commit 3ec6176d, rPi DASH pod and NS as CGM
* added manual glucose reading of 399
   * Manual glucose shows up on main screen as current glucose
   * Manual glucose does not appear in plot
   * Manual glucose appears with -- beside value in history
* applied the patch
   * Manual glucose now shows up in plot
   * Manual glucose appears with red drop beside value in history

**Comment by marionbarker** [comment]
Realized I had not tested deleting the manual Glucose entry. Returned and test that too. Works as expected.

**Review by marionbarker — DISMISSED** [review]

**Comment by MikePlante1** [comment]
> not sure of the configuration that @MikePlante1 referred to.


https://github.com/nightscout/Trio/assets/82073483/075a4bae-6e2c-4c52-bf86-00ecc504e9d6

**Comment by mountrcg** [comment]
Glucose dots for Glucose Simulator and Freestyle Simulator are drawn
| Test without filter adjustment | Filter adjusted |
| -- | -- |
| Simulator Screenshot - Dev 13 mini - 2024-06-26 at 11 56 47 | Simulator Screenshot - Dev 13 mini - 2024-06-26 at 11 53 17 |

**Comment by mountrcg** [comment]
> I just merged this into `alpha` to test this on a simulator.
> 
> I noticed this PR breaks the display when using "Glucose Simulator" for cgm, but it seems that's probably not really so much a problem with this PR as it is that readings from Glucose Simulator use `nil` for `type` instead of `sgv`.

yes the culprit was this PR! Fixed now - see above.

**Review by MikePlante1 — APPROVED** [review]
🚀 LGTM

**Review by dnzxy — APPROVED** [review]
LGTM. Thank you for addressing the small thing that broke simulator. 

Merging with 2 approvals and 2 successful tests (including Marion‘s).

**Comment by Sjoerd-Bo3** [comment]
Got sniped by @dnzxy there 🐌, But also LGTM!

**Pull request merged**
