### PR TITLE
gemfile update

### PR DESCRIPTION
**Pull request by mountrcg**
From the conversation @dnzxy and @marionbarker had on Discord. I updated the gemfile, as the error also occured in one of my repos. This gemfile fixed the error.

### CODE REVIEW

**Comment by marionbarker** [comment]
## Summary
Successful test

## Details
* I tested this by adding this version of Gemfile.lock to iAPS dev.
* The build action was [successful](https://github.com/loopdocs-tester/iAPS/actions/runs/9746625518) with this file.

### Background
* Previously, Gemfile.lock was removed completely from iAPS dev and main because an older version prevented the fastlane portion of the build action from succeeding.
* I previously tested by trying to build iAPS main with GitHub action using the commit before the Gemfile.lock was removed and demonstrated that it failed [Failure log](https://github.com/loopdocs-tester/iAPS/actions/runs/9733750879)

**Review by marionbarker — APPROVED** [review]

**Comment by bjornoleh** [comment]
@mountrcg , what was your errors, were they the same as in Marion’s failure log above? Were they consistent or only for some build attempts?

Anything that differs from Trio in GitHub actions or fastlane related code on your end?

**Comment by mountrcg** [comment]
@bjornoleh it was error 34 as well - no I don't think so - have just the same as iAPS in that repo fastlane wise. Was reported in iAPS channel on autoisf discord.

**Review by Sjoerd-Bo3 — APPROVED** [review]
LGTM Builds in Fastlane

**Pull request merged**
