### PR TITLE
Trio Release 0.2.0

### PR DESCRIPTION
**Pull request by tmhastings**
# Trio 0.2.0 trio
<details open><summary>expand details</summary><br>
<p>
This app splits from <i>Artificial-Pancreas/iAPS</i> at v2.3.3 on the main branch and <a href="https://github.com/nightscout/Trio/commit/f404fc49bfe4732dbb61c3a1b202d5b1f22ce178">this commit</a>. Very minimal UI changes were made in this initial update, but while it may look and for the most part seem the same as iAPS v2.3.3, you can see from the number of commits and files/lines of code changed in this PR that there are extensive changes under the hood. These changes were done to ensure it is truly open source, peer-reviewed and tested, to keep it in sync with updates from Loop's submodules (the stuff that connects your pump, CGM, and services), to fix some bugs, and to add a few new features.
</p></details>

## The Team
<details><summary>expand details</summary><br>
<p>
Trio is a collaborative project set up by members of the DIY community who welcome a peer reviewed, Open Source iOS implementation of the Oref/APS algorithm. 
<br><br>
The team consists of:
<br>
<ul>
<li>Software architects</li>
<li>Developers</li>
<li>Code reviewers</li>
<li>Designers</li>
<li>Testers</li>
<li>Documentation specialists</li>
<li>Project managers / agile coaches</li>
</ul>
Anyone who wants to contribute is welcome to join the team!
</p></details>

## The Name
<details><summary>expand details</summary><br>
<p>
“Trio” is inspired by several joint efforts:

<ul>
<li><b>Algorithm/CGM/Pump</b>: the three components that make up your DIY loop</li>
<li><b>Basal/CR/ISF</b>: the three main settings that, when tuned, treat your TxD</li>
<li><b>Carbs/Fat/Protein</b>: the three main food components that impact your blood glucose</li>
<li><b>FAX/iAPS/Trio</b>: the three stages of Oref/APS leading to the birth of Trio</li>
<li>In true DIY fashion, make the Trio definition individualized to you</li>
</ul>
</p></details>

## Hosted by The Nightscout Foundation
<details><summary>expand details</summary><br>
<p>
The most obvious change from iAPS, other than the name, is that the repository location has changed to be housed by <a href="https://www.nightscoutfoundation.org">The Nightscout Foundation</a>, alongside <a href="https://github.com/nightscout/cgm-remote-monitor">Nightscout</a> and <a href="https://github.com/nightscout/AndroidAPS">AndroidAPS</a>. The Nightscout Foundation has a long track record of facilitating innovation in DIY diabetes technology and stoking collaboration between many developers and projects. This will keep Trio in the hands of the community rather than a single individual, and ensure all development is peer-reviewed and tested before being released.
</p></details>

## New Bundle ID
<details open><summary>expand details</summary><br>
<p>
If you're switching to Trio from iAPS, another big change is the app's Bundle ID, which is now <code>org.nightscout.TEAMID.trio</code>. This means Trio will not overwrite the iAPS app on your iPhone, but all settings must be re-entered and all devices re-connected. Trio will need about 24 hours of data before the dynamic features can be enabled. 

**If you're using Omnipod DASH or Eros, you will have to pair a new pod to start using Trio, but all other devices can transfer mid-session.**
</p></details>

## New App Group
<details open><summary>expand details</summary><br>
<p>
Instead of using the Loop's App Group, <code>group.com.TEAMID.loopkit.LoopGroup</code>, Trio uses its own - <code>group.org.nightscout.TEAMID.trio.trio-app-group</code>. This prevents settings from being retained when deleting and reinstalling Trio while Loop or iAPS is also installed. You still need to delete xDrip4iOS to completely reset settings, though.
</p></details>

## New Icons
<details><summary>expand details</summary><br>
<p>
New icons have been created as a symbol of the name Trio.
(by @tmhastings, plus some old ones by @tqb43)<br>
logos
</p></details>

## Default Setting Changes
<details><summary>expand details</summary><br>
<p>
<ul>
<li><b>Default CGM</b>: <code>None</code> (instead of <code>Nightscout</code>)</li>
<li><b>Show high/low lines on main chart</b>: <code>On</code> (instead of <code>Off</code>)</li>
<li><b>High value for main chart lines and statistics</b>: <code>180</code> (instead of <code>145</code>)</li>
<li><b>Sensitivity Raises Target</b>: <code>Off</code> (instead of <code>On</code>)</li>
<li><b>Minimum Safety Threshold</b>: <code>60</code> (instead of <code>65</code>, which keeps it more in line with Oref0)</li>
<li><b>Adjustment Factor</b>: <code>0.8</code> (instead of <code>0.5</code>)</li>
</ul>
(by @MikePlante1 with input from @bjornoleh and many others)
</p></details>

## Sigmoid Adjustment Factor
<details><summary>expand details</summary><br>
<p>
With Dynamic ISF toggled on, the effects of <code>Adjustment Factor</code> vary drastically between having <code>Sigmoid</code> turned <code>on</code> and <code>off</code>. Because of this, we've split the <code>Adjustment Factor</code> in two and given Sigmoid its own setting. This allows <code>Adjustment Factor</code> to be defaulted to <code>0.8</code> with <code>Sigmoid</code> turned <code>off</code> and to <code>0.5</code> with <code>Sigmoid</code> turned <code>on</code>. (by @MikePlante1)
<br><br>
sigmoid settings
</p></details>

## External Insulin & Glucose
<details><summary>expand details</summary><br>
<p>
External insulin entry (to log non-pump insulin, eg. from an insulin pen) has been moved to the History screen rather than the Bolus screen. External insulin entries will display a warning if amount is larger than Max Bolus setting and will not be allowed if over three times the Max Bolus setting. The History screen also now displays if a bolus was an SMB or External, and uses swipe gestures to delete entries. (by @BrianWieder with many cherry picks from @dnzxy)
<br>
<table>
  <tr>
    <th>History (Treatments)</th>
    <th>History (Glucose)</th>
</tr>
  <tr>
    <td>historyInsulin</td>
    <td>glucoseHistory</td>
    </tr><tr>
    <th>Log External Insulin</th>
    <th>Log Glucose</th>
    </tr><tr>
    <td>maxExternalBolus</td>
    <td>logGlucose</td>
    </tr>
    </table>
</p></details>

## Distinguish Manual Glucose Readings
<details><summary>expand details</summary><br>
<p>
Manually entered glucose readings are now more noticeable in both the history and the main chart. (by @mountrcg)
<br><br>
<table>
<tr>
<th>Chart</th>
<th>History</th>
</tr>
<tr>
<td>chart</td>
<td>history
</tr>
</table>
</p></details>

## Edit Profile Overrides & Temp Targets
<details><summary>expand details</summary><br>
<p>
Swiping left on a saved profile override or temp target now gives you the option to edit or delete. Selecting to edit will open a new page where you can change the name and/or any of the settings. (by @dsnallfot)
<br><br>
<table>
<tr>
<th>Option to Edit/Delete</th>
<th>Editing a Profile Override</th>
</tr>
<tr>
<td>edit or delete</td>
<td>delete
</tr>
</table>
</p></details>

## LoopKit Submodules (pumps/cgms/services)
<details><summary>expand details</summary><br>
<p>
The code that's used to connect to pumps, CGMs, and other things was taken from their implementations in Loop. This release changes where that code is housed from within this app to point to the code in @LoopKit or @LoopAndLearn's repositories. This allows for a better development as it makes it easy to see the differences between the code used in Trio vs the code being used in LoopKit and allows updates in the LoopKit repo to easily be pulled into Trio and vice versa as submodules are improved in Trio and shared to LoopKit. (by @bjornoleh with help from @marionbarker and @bjornoleh)

Updates to submodules versus what was used in iAPS v2.3.3 (by @itsmojo with help from @marionbarker and others):
<ul>
<li>Use `appName` instead of `Loop` or `Trio` so both apps can share the same code but display their own name. This change is still be applied throughout the different submodules.</li>
<li>Reduced the battery load on pods by reducing the rate of getStatus calls to the pod to one third of the previous level without affecting all the other commanding needed to control the pod. This reduced battery load on pods</li>
<li>Updated to avoid triggering the <code>Critical Pod Fault 049 (0x31)</code> error which caused a pod loss.</li>
<li>Added Tidepool submodule to allow direct uploading instead of using Apple Health.</li>
<li>Fix display bug for Medtronic to show scheduled basal rate properly.</li>
<li>Now guards against time change while a bolus is in progress was added to prevent potential fatal crash requiring app deletion and rebuild</li>
<li>Indicate a change in time zone of phone in Medtronic Pump Manager</li>
</ul>
</p></details>

## Oref
<details><summary>expand details</summary><br>
<p>
This part is rather technical. Oref (the algorithm from <a href="https://github.com/openaps/oref0">OpenAPS</a> that drives Trio) is written in the JavaScript programming language. In order to perform well in an iOS app, the algorithm is implemented in a minimized format. Until the algorithm is rewritten into the Swift programming language, it needs to be like this to ensure performance. The source code used to build the minimized files is now included in <a href="https://github.com/nightscout/Trio/tree/dev/trio-oref">this repo</a> as well as a separate repo <a href="https://github.com/nightscout/trio-oref">trio-oref</a>. This work is quite extensive and has been done and peer-reviewed by several contributors: (beautified/reconstructed by @JeremyStorring and updated by @bjornoleh, @mountrcg, @avouspierre, @MikePlante1, @tmhastings)
</p></details>

## Schedule SMBs Off in Profile Overrides
<details><summary>expand details</summary><br>
<p>
The <code>Schedule when SMBs are Off</code> option in profile overrides has been improved to make it easier to understand and use. Now, if you want to disable SMBs for the entire time the override is active, toggle on <code>Always Disable SMBs</code>, but if you want to specify a timeframe for SMBs to be disabled, you can toggle off <code>Always Disable SMBs</code> toggle on <code>Schedule when SMBs are Off</code> and set the timeframe. Note that setting a timeframe of 22-6 would disable SMBs from 22:00 (10PM) through 5:59 as long as the override is active during that time.
<br><br>
schedule SMBs off
</p></details>

## Restart Bug Squashed
<details><summary>expand details</summary><br>
<p>
Since the beginning of FAX, there was a bug where restarting a phone could potentially cause a loss of pump or cgm connection. This was especially detrimental for Omnipod users, as there's no way to reconnect it after it's lost. The fix for this from LoopKit has now been added to Trio. (by @dnzxy, @kskandis, @avouspierre)
</p></details>

## Apple Health Fix
<details><summary>expand details</summary><br>
<p>
The 2.3.3 version of iAPS had a bug with Apple Health that would crash the app any time a loop cycle was run. This part of the code was re-written and fixed (by @AndreasStokholm), then thoroughly tested and peer-reviewed by the team. Unfortunately there are still problems with Apple Health, as it still creates an excessive amount of entries that significantly increases storage size and can cause AH to lag.
</p></details>

## Fix Multiple Meal Entry Bug
<details><summary>expand details</summary><br>
<p>
Some people have had the app freeze while entering a meal and mistakenly entered the same meal multiple times without realizing it. The <code>Save and continue</code> is now disabled as soon as it’s pressed to prevent that from happening. (by @MikePlante1)
</p></details>

## Fix mmol/L Glucose Target Bug
<details><summary>expand details</summary><br>
<p>
The bug causing glucose target to not be settable to certain mmol/L values has been fixed. (cherry-picked from @Jon-b-m by @Sjoerd-Bo3)
</p></details>

## Tidepool Integration
<details><summary>expand details</summary><br>
<p>
Tidepool can now be uploaded to directly from Trio instead of using Apple Health and the Tidepool app on your iPhone. Note that if both are enabled, you will see duplicate entries in Tidepool, and even after turning one off, you could still see up to a week of duplicate data. (by @avouspierre)
<br><br>
Tidepool

</p></details>

## Dexcom Share Integration
<details><summary>expand details</summary><br>
<p>
Dexcom Share has been fixed so it can now be used as a CGM source. Also, if you use Dexcom G6 as your CGM and you enter your Dexcom Share credentials at the bottom in <code>⚙️ > CGM > CGM Configuration</code>, missed readings should backfill in Trio from Dexcom Share. Keep in mind, though, when you change G6 transmitters Trio will continue to pull readings from Dexcom Share causing you to rely on internet for readings until you update your G6 Transmitter ID in Trio. (by @avouspierre)
</p></details>

## Meal Settings
<details><summary>expand details</summary><br>
<p>
There is a new section in settings called <code>Meal Settings</code>. In it, you'll find <code>Max Carbs</code> (which used to be in <code>Pump Settings</code>), <code>Max Fat</code>, <code>Max Protein</code>, and the <code>Fat and Protein Conversion Settings</code> that used to be found in it's own section. (by @bjornoleh)

<table>
<th>⚙️</th>
<th>Meal Settings</th>
<tr>
<td>meal settings1</td>
<td>meal settings2</td>
</tr>
</table>
</p></details>

## Max Macros
<details><summary>expand details</summary><br>
<p>
<ul>
<li>Two new settings added: <code>Max Fat</code> & <code>Max Protein</code></li>
<ul>
<li>Both are defaulted to 250g to match <code>Max Carbs</code>' default</li>
</ul>
<li>Label of <code>Carbohydrate limit</code> changed to <code>Limit Per Entry</code> for Meal Settings</li>
<li>Shortened <code>grams</code> to <code>g</code> for the meal entry screen</li>
<li>If carbs, fat, or protein exceed their limit:</li>
<ul>
<li>Changes <code>g</code> to <code>⚠️</code></li>
<li>Disables submit button, changes text to red, and replaces with warning</li>
</ul>
</ul>

https://github.com/nightscout/Trio/assets/82073483/649f2677-8146-4328-9dd7-5371aec8e4ec
</p></details>

## Max Bolus
<details><summary>expand details</summary><br>
<p>
Manually entering a bolus larger than the <code>Max Bolus</code> setting used to just deliver the max bolus amount, but now this setting prevents the bolus from being delivered until the amount is less than or equal to the max setting. (cherry-picked from @Jon-b-m and modified by @MikePlante1 with input from @bjornoleh)
<br><br>
Also now displays the value read from the pump instead of from settings to ensure the correct value is shown. Important for Medtronic pumps and in the future for Dana pumps. (by @bastiaanv and ported by @dnzxy)
<br><br>
Max Bolus
</p></details>

## Live Activities (Dynamic Island & Lockscreen Widget)
<details><summary>expand details</summary><br>
<p>
Live Activities have been added to show relevant data without opening Trio. This displays glucose, delta, and trend on the lock screen (iOS 16.2+) as well as in the Dynamic Island (iPhone 14+). Optionally, a glucose graph and current IOB & COB can also be displayed. Consistently updated every 5 minutes with every loop cycle. (cherry-picked from @nas10, @polscm32 and ported by @MikePlante1)

Turn Live Activity on and switch between display options by going to ⚙️ > <code>Notifications</code> 

<table>
<th>Live Activity</th>
<th>Screenshot</th>
<tr>
<td>Lockscreen (simple)</td>
<td>LA lockscreen simple</td>
</tr><tr>
<td>Lockscreen (detailed)</td>
<td>LA lockscreen detailed</td>
</tr><tr>
<td>Dynamic Island</td>
<td>LA dynamic island</td>
</tr><tr>
<td>Dynamic Island<br>(long press)</td>
<td>LA Dynamic Island graph</td>
</tr>
</table>
</p></details>

## Dexcom ONE+
<details><summary>expand details</summary><br>
<p>
Added support for Dexcom ONE+ (taken from <a href="https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Dexcom.20One.2B.20.28new.20sensor.20in.20Europe.29/near/421012782">this Zulip discussion</a>)
</p></details>

## Nightscout Menu Updated
<details><summary>expand details</summary><br>
<p>
The menu for Nightscout has been updated to include sub-menus. The new <code>Fetch Treatments</code> toggle controls whether Trio will fetch carbs and temp targets from Nightscout. The duplicate <code>Remote Control</code> toggle has also been removed from <code>Preferences</code>. (by @dsnallfot)
<br><br>
<table>
<th>⚙️ > Nightscout</th>
<th>Connect</th>
<tr>
<td>Nightscout</td>
<td>Connect</td>
</tr><tr>
<th>Upload</th>
<th>Fetch and Remote Control</th>
</tr><tr>
<td>Upload</td>
<td>Fetch and Remote Control</td>
</tr>
</table>
</p></details>

## Import Settings From Nightscout
<details><summary>expand details</summary><br>
<p>
Fixed this so it now also works for mg/dL. Also now allows importing from settings saved to Nightscout from Loop and will use the center of your correction range from Loop for the target range in Trio. (by @kskandis and @MikePlante1)

Settings imported: 
<ul>
<li>Basal Profile</li>
<li>Target Glucose</li>
<li>Insulin Sensitivities</li>
<li>Carb Ratio</li>
<li>DIA</li>
</p></details>

## Improve Nightscout Uploads
<details><summary>expand details</summary><br>
<p>
Previously, only enacted loop cycles were uploaded to Nightscout, which caused information gaps from loop cycles that were just suggested but not actually enacted for one reason or another. Now suggested loop cycles will also be uploaded as well. (by @bjornoleh and suggested by @scottleibrand)
</p></details>

## Fat & Protein Upload to Nightscout
<details><summary>expand details</summary><br>
<p>
Fat & Protein are now uploaded to Nightscout when you announce them in Trio. (by @aug0211)
image
</p></details>

## FPU Conversion
<details><summary>expand details</summary><br>
<p>
Oref ignores any carb entry less than 1.0g. This used to happen when <code>Interval In Minutes</code> was set low and/or the amount of fat and protein was small. Now, the carb entries that were converted from fat & protein are saved to ensure they are always at least 1g each and not ignored by oref. (by @dnzxy)

For example, with the default <code>Meal Settings</code>, 10g of protein and 5g of fat used to converted into 7 entries of 0.7g carbs. Now, it will be converted into 5 entries of 1g carbs. 
</p></details>

## Statistics Range
<details><summary>expand details</summary><br>
<p>
The statistics screen now includes the <code>high</code> and <code>low</code> values in the normal range instead of the high and low ranges. This matches the colors of the glucose dots that were already being used on the Statistics screen. (by @MikePlante1)

For this example in a simulator, I kept <code>high</code>/<code>low</code> to the default <code>70</code>/<code>180</code> and manually entered these values:

<table>
<th>Readings</th>
<th></th>
<tr>
<td>glucose values</td>
<td></td>
</tr>
<tr>
<th>Trio (standing)</th>
<th>Trio (laying)</th>
</tr>
<tr>
<td>new standing</td>
<td>new laying</td>
</tr>
<tr>
<th>iAPS 2.3.3 (standing)</th>
<th>iAPS 2.3.3 (laying)</th>
</tr>
<tr>
<td>old standing</td>
<td>old laying</td>
</tr>
</table>
</p></details>

## Pump Status Icons
<details><summary>expand details</summary><br>
<p>
New icons are displayed when your pod status has a warning or critical message. This will help highlight when a problem occurs with the pump to help make the user aware of the issue. (by @avouspierre)
<br><br>

<table>
<th>Pump Warning</th>
<th>Pump Critical</th>
<tr>
<td>Pump Warning</td>
<td>Pump Critical</td>
</tr>
</table>
</p></details>

## Display icons/buttons when no pump/CGM is selected
<details><summary>expand details</summary><br>
<p>
When there is no pump or CGM selected, a button is displayed that will take you to the selection screen for pump or CGM. This does not affect instances where a pump or CGM *is* selected and just not paired. (by @avouspierre)
<br><br>
When Omnipod is removed as a pump source, it will now display <code>Add pump</code> rather than the erroneous <code>No pod</code> warning. (by @kskandis)
<br><br>
no pump cgm
</p></details>

## Confirm Bolus Faster on Apple Watch
<details><summary>expand details</summary><br>
<p>
An option has been added in ⚙️ > <code>Watch</code> to require less of a turn of the Apple Watch crown to confirm a bolus. (by @MikePlante1, who likes to confirm boluses with his nose)

https://github.com/nightscout/Trio/assets/82073483/407bd997-60c8-4c28-b7a2-a25b46ea63a3
</p></details>

## Hide Keyboard and Delete All Buttons added
<details><summary>expand details</summary><br>
<p>
There are now buttons on the keyboard to delete all text and to hide the keyboard. (by @polscm32)
<br><br>
Dismiss or Delete

</p></details>

## mmol/L <-> mg/dL Rounding Improved
<details><summary>expand details</summary><br>
<p>
A bug was fixed where entering certain mmol/L manual entries were saved incorrectly due to rounding, such as 7.1 -> 7.0.

</p></details>

## Eventual Glucose Rounding for mmol/L
<details><summary>expand details</summary><br>
<p>
Eventual Glucose now rounds to 1 decimal place for mmol/L users instead of 2 on the main screen as well as the watch app.
<br><br>
Screenshot 2024-07-15 at 10 14 06 PM

</p></details>

## Tests Enabled
<details><summary>expand details</summary><br>
<p>
Added ability to run tests on Trio and submodules. (by @avouspierre)
</p></details>

## Browser Build Updates
<details><summary>expand details</summary><br>
<p>
Browser Build updated to new Apple/GitHub standards. (by @bjornoleh)
TestFlight Expiration is now displayed in Settings. (by @bjorkert)
Gemfile updated. (by @mountrcg)
</p></details>

## Guardrails
<details><summary>expand details</summary><br>
<p>
Guardrails to prevent preferences from being set outside a reasonable range can now be set in the code, although no guardrails have been added yet at this time. (by @JeremyStorring)

To add a guardrail, add <code>minVal</code> and/or <code>maxVal</code> to the <code>type</code> in <code>FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorStateModel.swift</code>. For example, to restrict <code>Minimum Safety Threshold</code> from 60-120, use the following:

<pre style="white-space: pre-wrap; word-wrap: break-word;"><code>
Field(
    displayName: NSLocalizedString("Minimum Safety Threshold (mg/dL)", comment: "Minimum Safety Threshold"),
        type: .decimal(keypath: \.threshold_setting, minVal: 60, maxVal: 120),
        infoText: NSLocalizedString(
            "All insulin will be suspended if your glucose is predicted to drop below the safety threshold.\n\nMust be set between 60-120 mg/dL.\nTo convert from mmol/L, multiply by 18.\n\nNote: Basal may be resumed if there's negative IOB and glucose is rising faster than predicted.",
        comment: "Minimum Safety Threshold"
    ),
    settable: self
)
</code></pre>
</p></details>

## Disabled Saving Autotune to Pump
<details><summary>expand details</summary><br>
<p>
Removed the button for this functionality until it can be fixed, since 0 U/hr basal rates were causing issues with this feature. Don't worry, this feature will return.
</p></details>

## Removed Stats Upload
<details><summary>expand details</summary><br>
<p>
Removed the option to upload Statistics to Nightscout, since it is no longer compatible with the website this feature was added for before. (by @MikePlante1)
</p></details>

## List of individual PRs included in this large PR:
<details><summary>expand details</summary><br>
<p>
<ul>
<li>#1</li>
<li>#3</li>
<li>#5</li>
<li>#6</li>
<li>#14</li>
<li>#15</li>
<li>#17</li>
<li>#19</li>
<li>#22</li>
<li>#26</li>
<li>#28</li>
<li>#31</li>
<li>#34</li>
<li>#36</li>
<li>#39</li>
<li>#41</li>
<li>#42</li>
<li>#43</li>
<li>#46</li>
<li>#48</li>
<li>#50</li>
<li>#52</li>
<li>#55</li>
<li>#59</li>
<li>#60</li>
<li>#61</li>
<li>#62</li>
<li>#63</li>
<li>#66</li>
<li>#67</li>
<li>#68</li>
<li>#72</li>
<li>#74</li>
<li>#75</li>
<li>#76</li>
<li>#78</li>
<li>#79</li>
<li>#80</li>
<li>#81</li>
<li>#82</li>
<li>#83</li>
<li>#86</li>
<li>#89</li>
<li>#90</li>
<li>#91</li>
<li>#93</li>
<li>#94</li>
<li>#95</li>
<li>#97</li>
<li>#99</li>
<li>#100</li>
<li>#101</li>
<li>#103</li>
<li>#110</li>
<li>#112</li>
<li>#114</li>
<li>#116</li>
<li>#117</li>
<li>#118</li>
<li>#120</li>
<li>#121</li>
<li>#122</li>
<li>#124</li>
<li>#125</li>
<li>#127</li>
<li>#128</li>
<li>#134</li>
<li>#135</li>
<li>#140 </li>
<li>#141</li>
<li>#143</li>
<li>#143</li>
<li>#148</li>
<li>#149</li>
<li>#150 </li>
<li>#151</li>
<li>#155 </li>
<li>#156 </li>
<li>#157</li>
<li>#160 </li>
<li>#163</li>
<li>#164</li>
<li>#165</li>
<li>#166</li>
<li>#168 </li>
<li>#169 </li>
<li>#170 </li>
<li>#172 </li>
<li>#173</li>
<li>#176 </li>
-- 2024-05-13: Repository opened for beta testing -- 
<li>#179 </li>
<li>#180 </li>
<li>#184 </li>
<li>#197 </li>
<li>#202 </li>
<li>#206 </li>
<li>#215 </li>
<li>#218 </li>
<li>#221 </li>
<li>#224 </li>
<li>#225 </li>
<li>#226</li>
<li>#227 </li>
<li>#230 </li>
<li>#232 </li>
<li>#235 </li>
<li>#236 </li>
<li>#240 </li>
<li>#248 </li>
<li>#249 </li>
<li>#253 </li>
<li>#260 </li>
<li>#266 </li>
<li>#275 </li>
<li>#277 </li>
<li>#279 </li>
<li>#280 </li>
<li>#281 </li>
<li>#282 </li>
<li>#284 </li>
<li>#285 </li>
<li>#290 </li>
<li>#292 </li>
<li>#297 </li>
<li>#299 </li>
<li>#306 </li>
<li>#307 </li>
<li>#308 </li>
<li>#310 </li>
<li>#314 </li>
<li>#320 </li>
<li>#321 </li>
<li>#322 </li>
<li>#323 </li>
<li>#326 </li>
<li>#329 </li>
<li>#330 </li>
<li>#332 </li>
<li>#333 </li>
<li>#334 </li>
<li>#337 </li>
<li>#338 </li>
<li>#340 </li>
<li>#342 </li>
<li>#352 </li>
<li>#353 </li>
<li>#355 </li>
<li>#356 </li>
<li>#359 </li>
<li>#362 </li>
<li>#365 </li>
<li>#366 </li>
<li>#367 </li>
-- 2024-07-29: 0.2.0-rc1 created --
<li>#369 </li>
<li>#370 </li>
<li>#372 </li>
<li>#374 </li>
<li>#376 </li>
<li>#377 </li>
<li>#378 </li>
<li>#382 </li>
<li>#383 </li>
</ul>
</p></details>

## Go Team!🎉
<details><summary>expand details</summary><br>
<p>
Thank you to the following developers who have added commits to this PR and the initial version of Trio:
@AndreasStokholm, @avouspierre, @bjorkert, @bjornoleh, @BrianWieder, @dnzxy, @dsnallfot, @JeremyStorring, @kskandis, @kylmcw, @lifeguardz, @marionbarker, @MikePlante1, @mountrcg, @polscm32, @Sjoerd-Bo3, @tmhastings

A heartfelt thank you to everyone who has played a crucial role behind the scenes with their valuable contributions in discussions, project management, coaching, documentation, testing, and more:
- Dana Lewis (@danamlewis) and Scott Leibrand (@scottleibrand) for their unwavering support and guidance regarding our Oref inquiries.
- Tim Street for his invaluable insights into the implementation of Oref code.
- Tim Gunn (@Tornado-Tim) for his dedicated efforts in setting up and maintaining the Nightscout hosting of the Trio repository.
- Auggie Fisher (@aug0211) for generously sharing the Discord server for Trio and providing ongoing support for both current and future developments of Trio's caregiver implementation.
- Pete Wilkins (@petewilkins) for optimizing the Trio Discord home base throughout development and in anticipation of future discussions.
- Marion Barker (@marionbarker) for her invaluable contributions, including creating the Build Scripts for Trio, enhancing documentation, and offering expertise in various areas not fully reflected on Github.
- Mike Plante (@MikePlante1) for getting involved in almost every aspect of the release and development. Without your continued dedication this could not have started nor could it have finished!
- Sjoerd Bozon (@Sjoerd-Bo3) and Bjørn Ole (@bjornoleh) for their tireless efforts in driving collaboration and continuously advancing the project.
- Kelsey Huss (@kelseyhuss) for stepping up without hesitation to communicate progress to the community.
- Theresa Hastings (@tmhastings) for pulling **all** the strings, getting the right people involved and spending much of her days on this project one way or another. Without you this would never have happened!
- Tom Barrows (@tqb43) for sharing your branding and logo expertise and providing support to users in the Facebook group.
- Magnus Reintz (@t1dude) for his consistent availability (🦇) and invaluable assistance with Facebook community management, clear language and translation management.
- Jonas Hummelstrand for his commitment to maintaining open communication on Facebook, even during challenging times.
- Dan (@dnzxy) for consistently fostering discourse aimed at enhancing and enriching the DIY community and Trio project.
- To Dan, Marvin, Andreas, Mike, Tom, Magnus, Kelsey, and Theresa, Trio owes you its inception. Your proactive approach and DIY spirit didn't just recognize the critical safety aspect but also reshaped the implementation of Oref on iOS. Your bold actions turned necessity into reality. Thank you for your invaluable contributions.
</p></details>

### CODE REVIEW

**Review by kelseyhuss — DISMISSED** [review]

**Comment by pheltzel** [comment]
@t1dude @tmhastings Could I get a shoutout as an agile coach? I kid. Actually, based on Theresa's brilliant idea to take up NS on their offer to host Trio, I reached out to James Wedding and introduced him to @AndreasStokholm -- and James said: Whatever you need. I believe it took several others to get the repo set up in NS, and in fact, at one point it was at the wrong NS domain. And super early on I suggested we use some of Princeton's “Ground Rules for Respectful Discussion” which after much work by @aug0211 became a code of conduct, which I thought was really important to set the stage early on to avoid what had happened in the past. Any mention of any of this would be appreciated, tiny as it is, b/c this stuff is really important to me as I know it is to all of us. thank you!

**Review by aug0211 — APPROVED** [review]
It’s time! Months of testing and iterating in vivo and in vitro from dozens of contributors and testers. Good work team!

**Review by AndreasStokholm — APPROVED** [review]

**Review by Sjoerd-Bo3 — APPROVED** [review]
### Looks VERY good to me! 
Team, what a combined effort! Already looking forward to 1.0, that holds all our really good stuff!!

**Review by MikePlante1 — APPROVED** [review]

**Review by marionbarker — APPROVED** [review]
LGTM

**Review by bjornoleh — APPROVED** [review]
Let's do this!

Confirmed to build with Xcode.

**Review by dnzxy — APPROVED** [review]
Let’s push the boundaries of what's possible together. For diabetics and DIY. #WeAreNotWaiting

**Review by avouspierre — APPROVED** [review]
😃

**Review by JeremyStorring — APPROVED** [review]
Excellent work everyone! :)

**Review by t1dude — APPROVED** [review]
Approved :)

**Pull request merged**
