### PR TITLE
Fix for setting of BG Targets

### PR DESCRIPTION
**Pull request by Sjoerd-Bo3**
Implemented the iAPS fix https://github.com/Artificial-Pancreas/iAPS/pull/715/files that closes Issue #318

### CODE REVIEW

**Comment by Sjoerd-Bo3** [comment]
closes Issue https://github.com/nightscout/Trio/issues/318

**Review by bjornoleh — APPROVED** [review]
Approving based on testing with GH build. Did not check for uncommitted changes after the build, or do significant code review. 

Tested successfully setting target values of:
4
4,1
6
6,1
6,2
10

**Comment by marionbarker** [comment]
### Summary
I confirm Issue #318 is fixed with this patch

### Testing
Tested by applying patch to alpha commit 82f2d01a 

* built on existing Trio, SE running iOS 17.5.1
* units already mmol/L from testing the issue earlier (see [comment](https://github.com/nightscout/Trio/issues/318#issuecomment-2173738509))
   * modify target, save, go to settings, return to target screen:
      * choose 6.0; final 6.0 
      * choose 6.1; final 6.1 
      * choose 6.2; final 6.2
      * choose 4.0, final 4.0
      * choose 10.0, final 10.0

**Review by marionbarker — APPROVED** [review]

**Review by dnzxy — APPROVED** [review]

**Comment by dnzxy** [comment]
Bandaid fix for now, we generally a more thought out handling of mmol values; handle everything in mg/dl and only display in mmol. 

This fixes #318 and LGTM. Merging with 3 approvals.

**Pull request merged**
