### PR TITLE
Fix the dexcom share in Trio

### PR DESCRIPTION
**Pull request by avouspierre**
The PR allows to fetch BG of Dexcom share as a CGM as well as to fetch BG of Dexcom share with the Dexcom G6 CGM.

The PR updates the logic of the CGM fetch for all CGM based on Loop submodules (PluginSource).

## Test requirements  
- Activate the dexcom share in the Dexcom App in the IRL device 
- Check the dexcom share is operational with the dexcom follower apps

## 1. - IOS Simulator - Add Dexcom Share CGM 
- enter credentials
- the BG is updated immediatly :✅
- the BG is updated after 5 minutes  ✅

## 2. - Iphone 8 - Add G6 CGM 
- enter a fake number for the G6 CGM
- enter credentials for dexcom share 
- the BG is fetched and updated immediatly ✅
- the BG is updated after 5 minutes with the use of the dexcom share  ✅

## 3. - iphone 15 - Add G6 CGM with G6 sensor
- enter the correct number for the G6 sensor
- enter credentials for dexcom share ✅
- the BG is updated after 5 minutes with the use of the “BLE” heartbeat. ✅

Need to be tested with Libre and Dexcom G7.  Both implement the fetchIfNeeded function with noData response.

### CODE REVIEW

**Review by bjornoleh — DISMISSED** [review]
Tested: 

Builds to Xcode simulator ✅ 
Received data when configured as CGM ✅ 
Received data when used with fake G6 ✅ 

Without having a full understanding of the code changes, this looks good to me!

**Comment by Sjoerd-Bo3** [comment]
Going to test on G7

**Comment by marionbarker** [comment]
### Summary
Success - works with phone locked so long as pump has a heartbeat.

### Configuration
* iPhone SE running iOS 17.5.1
* Pump is rPi DASH pod (has a heartbeat)
* Trio dev commit 32b5e953
* apply patch from PR 282

### Testing
* Stop using NS as CGM
* Add Dexcom Share
   * Wait 2 CGM updates, ensure CGM data continues (success)
* Lock phone
   * Wait 15 minutes, unlock to confirm looping while locked, green loop with dosing history while locked (success)

**Review by marionbarker — DISMISSED** [review]
Approve based off testing.

**Review by Sjoerd-Bo3 — APPROVED** [review]
This does not close #287 Only for G6 it does.

**Review by MikePlante1 — APPROVED** [review]
LGTM based on testing. I did not review code, but did notice no linting occurred when building (only Package.resolve was changed)

Tested in a simulator phone using Dexcom Share as the cgm source. Took a couple minutes before it was backfilled, but then it backfilled 6 readings (30 minutes). After that, the simulator populated readings within 2 seconds of the readings appearing on my real phone in the Dexcom G6 app.

Details for following tests: 
Device: iPhone 14 Pro Max
OS: iOS 17.5.1
Pump: Omnipod Eros + OrangeLink
CGM: Anubis + Dexcom G6 app, Transmitter & Share credentials added in Trio
Trio: This PR built on top of the current `dev` (https://github.com/MikePlante1/Trio/commit/00881fa90fcc54e9b673e12fb3a6fc267a5afb9a)

I tried to test backfilling by sticking my phone in the microwave for one cycle, leaving my phone on the other side of the office, or disabling bluetooth... all of which did cause a missed reading, but when the next reading was populated in the G6 app, the G6 app never backfilled the missed reading, which means I couldn't test backfilling G6 in Trio.

So then I tried closing all the apps on my phone, including Trio, but kept the G6 app running. The missed readings (in Trio, as G6 app did not have any missing readings) were populated as soon as Trio was opened and a loop cycle was triggered immediately. When this happens too close to the next cgm reading, the loop cycle is skipped for the next cgm reading as a loop cycle was completed too recently.

**Review by MikePlante1 — CHANGES_REQUESTED** [review]
Should this target alpha instead of dev?

**Comment by bjornoleh** [comment]
> Should this target alpha instead of dev?

I changed the base branch, which apparently dismisses all previous reviews… Can you resolve the change request? I can’t do that it seems.

**Review by bjornoleh — APPROVED** [review]

**Review by marionbarker — APPROVED** [review]
### Summary
I should have just approved again because only change was the base branch.
* I seem to be incapable of doing that (did a successful test again)

### Test details
* started with latest alpha, commit d7a730c4 with rPi attached to phone
   * applied the patch
   * selected Dexcom Share
   * set Closed Loop to enabled
   * locked the phone and set timer to 15 minutes
      * unlocked phone to green loop with several adjustments to tempbasal while locked.

**Review by MikePlante1 — APPROVED** [review]

**Comment by bjornoleh** [comment]
Merging with three approvals

**Pull request merged**
