### PR TITLE
LiveActivity.swift: widget URL string "Trio://"

### PR DESCRIPTION
**Pull request by bjornoleh**
Replaces widgetURL(URL(string: "freeaps-x://"))

Related to #136

### CODE REVIEW

**Review by JeremyStorring — APPROVED** [review]

**Review by marionbarker — COMMENTED** [review]
I am not sure how the  widgetURL is used. 
The modification looks reasonable from code review.
Does this mean a shortcut on the phone requires an update?

**Comment by bjornoleh** [comment]
Tapping the Live activity widget was unaffected by the change (app opened before and after). But Trio:// is the correct url for whatever it's used for.

**Review by MikePlante1 — APPROVED** [review]

**Comment by MikePlante1** [comment]
I concur with bjornoleh. Tested opening the app from both the lockscreen widget and the Dynamic Island both before and after applying this PR on a real phone and it worked as usual. Not really sure what (if anything) it affects.

Should it maybe use APP_URL_SCHEME from Config, though? Just a thought. Hardcoding to Trio seems to be fine, though.

**Comment by bjornoleh** [comment]
I didn't quickly figure out how to use APP_URL_SCHEME here, so went with the hardcoded way instead. Shone more than good enough for this anyways.

**Comment by MikePlante1** [comment]
Actually... I even just deleted that line completely and it still seems to work fine. 🤷 So not sure what it's even for.

**Comment by MikePlante1** [comment]
Merging this with several approvals and it seems it could even be deleted.

**Pull request merged**
