### PR TITLE
add observer on pump deactivated to initialize pump status

### PR DESCRIPTION
**Pull request by kskandis**
This resolves Issue [Home View shows "No Pod" or "Signal Loss" despite insulin delivery system removal](https://github.com/nightscout/Trio/issues/283#top)
#283 

Tested Omnipod and Medtronics on Simulator

### CODE REVIEW

**Review by bjornoleh — APPROVED** [review]
Tested successfully in Xcode simulator (iPhone 15):

Before fix: Added Dash and removed the pump, the "No pod" warning appears also after removal
After fix: Added Dash and removed the pump, "Add pump" is displayed instead.

I did not review the code changes thoroughly, although I get the gist of it.

**Review by dnzxy — APPROVED** [review]
I've tested this pre-PR via a `.patch`-file. Worked as intended.

Tested with rPi pod simulator, in-app simulator on an iPhone 11 @ iOS 16.7.

LGTM

**Comment by bjornoleh** [comment]
Merging with two approvals 

Great job, @kskandis!

**Comment by marionbarker** [comment]
Testing after merge for completeness.

### Status
* Success for Pods
* Success for MDT

### Configuration
* iPhone SE iOS 17.5.1
* Trio dev, commit 9654d70a

### Testing
* Add Omnipod DASH
   * Deactivate pod and see No Pod on main screen
   * Switch to other delivery and see Add pump on screen
* Add Medtronic pump, succeeds
   * Delete Medtronic pump and see Add pump on screen.

**Pull request merged**
