### PR TITLE
Fix Discord URL

### LINKED ISSUE #410: Discord URL
What's the new discord URL? The docs version has expired

### PR DESCRIPTION
**Pull request by tonypartridge**
Resolves #410

### CODE REVIEW

**Review by dnzxy — DISMISSED** [review]
I rebased this onto dev. 

LGTM. Thanks, Tony.

**Review by Sjoerd-Bo3 — DISMISSED** [review]
LGTM and the links tunnels your to the right place!

**Comment by tonypartridge** [comment]
> I rebased this onto dev.
> 
> LGTM. Thanks, Tony.

Great, I'll use Dev in future for any PR's. Excited for this app.

**Comment by marionbarker** [comment]
I get failure to load for https://discord.diy-trio.org/

If I remove the `https://` or just drop the “s” it loads fine.

**Comment by Sjoerd-Bo3** [comment]
> I get failure to load for https://discord.diy-trio.org/
> 
> If I remove the `https://` or just drop the “s” it loads fine.

It was working for me.... Weird. @MikePlante1 ?

**Comment by Sjoerd-Bo3** [comment]
> > I get failure to load for https://discord.diy-trio.org/
> > If I remove the `https://` or just drop the “s” it loads fine.
> 
> Same now, it was working...... Likely ssl issue? We could update to use non-ssl but I think it would make more sense for the server issue handling the ssl/mapping to be resolved.

Yes, let's wait for @MikePlante1 He configured the link

**Comment by MikePlante1** [comment]
After talking with Namecheap customer support, looks like https:// isn't going to work. If you could please update it to http://discord.diy-trio.org

**Comment by tonypartridge** [comment]
> After talking with Namecheap customer support, looks like https:// isn't going to work. If you could please update it to http://discord.diy-trio.org

Updated as requested.

**Review by MikePlante1 — APPROVED** [review]
Links work for me now. Thanks!

**Review by Sjoerd-Bo3 — APPROVED** [review]

**Pull request merged**
