### PR TITLE
Update feat/dana to dev branch for Trio and DanaKit

### PR DESCRIPTION
**Pull request by marionbarker**
* I thought it better to leave the .gitmodules pointing to bastiaanv repository for now.
* One less indirection as Basiaan adds improvements to his repository
* This PR brings this feat/dev branch up to date with dev as of today.
* There are a lot of commits, but the file diffs should be appropriate

 % git diff dev update_feat/dana --name-status                     
M       .gitmodules
M       CGMBLEKit
A       DanaKit
M       FreeAPS.xcodeproj/xcshareddata/xcschemes/Trio.xcscheme
M       FreeAPS/Sources/APS/DeviceDataManager.swift
M       FreeAPS/Sources/Modules/PumpConfig/PumpConfigDataFlow.swift
M       FreeAPS/Sources/Modules/PumpConfig/View/PumpConfigRootView.swift
M       FreeAPS/Sources/Modules/PumpConfig/View/PumpSetupView.swift
M       LoopKit
M       MinimedKit
M       Trio.xcworkspace/contents.xcworkspacedata
M       scripts/swiftformat.sh

### CODE REVIEW

**Comment by marionbarker** [comment]
## Summary - Mac-Xcode
* build using this branch with Mac and Xcode
* this PR includes the modifications from PR #329
* successful build and install on test phone.

## Summary - Browser Build
* build using GitHub actions
* successful build and install on test phone

**Comment by Rig22** [comment]
I've been using the Dana driver for a while now and I can say that it's stable enough for me. The only drawback is the missing heartbeat. Because of the "silent ton enabled", I have to recharge my iPhone 14 Pro once a day. Normally the battery easily lasts the whole day. Otherwise I'm very satisfied.😀 Thanks to Bastiaan. 🙏

**Comment by bastiaanv** [comment]
The DanaKit submodule is synced to the correct and stable version of the driver. I cannot speak about the other changes, but they are looking good!

**Review by Sjoerd-Bo3 — APPROVED** [review]
LGTM Mergingin with Bastiaans blessing aswell

**Pull request merged**
