### PR TITLE
Update Submodules - Fixes Xcode 16 slow build plus other updates

### PR DESCRIPTION
**Pull request by marionbarker**
## Main Goal

The primary item fixed in this PR is Issue #423.

## Added updates

In addition, pick up other submodule fixes that are in the loopandlearn/submodule:trio branches but not yet added to Nightscout/Trio:dev workspace.

### Information for reviewers.

* Most of these changes are obvious from the notes below
* LoopKit may be confusing
    * In addition to the Xcode 16 build speed up change (the `pxbproj` file) there are two other files modified that are only used by Loop
        * fix an Export Critical logs error
        * fix an error when rearranging Overrides on the Loop screen
* LibreTransmitter
    * In addition to the Xcode 16 build speed up change (the `pxbproj` file, another modification was brought in to prevent notification when not enabled

Summary of submodules changed with this PR:
```
Submodules changed:

* CGMBLEKit 15af9cf...b786e8b (1):
  > Merge branch 'LoopKit:dev' into trio

* G7SensorKit b5e992e...2be3eb2 (1):
  > Add ONE+ to the display name (#28)

* LibreTransmitter fb83de0...0848e26 (3):
  > Merge pull request #3 from dnzxy/module-verify
  > Merge branch 'LoopKit:main' into trio
  > Merge pull request #2 from loopandlearn/loopkit-pr-15

* LoopKit 6d9b19ab...a5c1d668 (2):
  > Merge pull request #3 from dnzxy/module-verify
  > Merge branch 'LoopKit:dev' into trio

* OmniBLE e398345...4ad8117 (2):
  > Merge pull request #131 from dnzxy/module-verify
  > Merge pull request #128 from loopandlearn/fix/deactivate-sideways-pull

* OmniKit 849dc7a...01bc598 (2):
  > Merge pull request #40 from dnzxy/module-verify
  > Merge pull request #39 from loopandlearn/fix/deactivate-sideways-pull
```

### CODE REVIEW

**Comment by marionbarker** [comment]
Notes about most recent commit:
* The LoopKit/LibreTransmitter:`main` branch was updated
* The loopandlearn/LibreTransmitter:`trio` branch was updated to match
* The SHA for the `trio` branch updated because of the merge commit
* No change to the code with this commit - housekeeping task to add the update

**Comment by marionbarker** [comment]
These updates to the SHA for the LoopKit submodules aligns with the version for these submodules just released in Loop 3.4.3.

Since last comment, I added commits so code matches the LoopKit/LibreTransmitter:main branch and LoopKit/LoopKit:dev branch and SHA match the values found in loopandlearn/*:trio branch.

This latest update for the LoopKit submodule is improvement in visibility for CheckmarkListItems, especially important for dark mode with iOS 18 devices.

Graphic shows screen from previous code on left and updated code on the right.

original_revised_dark

**Review by bjornoleh — APPROVED** [review]
Builds to sim, can confirm G6+ and G7+ text is updated, and otherwise involves very few changes to code. 

No uncommitted changes after building.

**Review by dnzxy — APPROVED** [review]

**Comment by dnzxy** [comment]
Merging with 2 approvals.

**Pull request merged**
