### PR TITLE
Add Dana option to built-in pump simulator

### PR DESCRIPTION
**Pull request by marionbarker**
This adds Dana as an option for the pump simulator for the Trio app. 

## Problem with this PR
This may be an existing Trio issue that is revealed by this PR.

I set Max Bolus and Max Basal to the allowed values for Dana (80U and 35 U/hr) and that was accepted when the in-app simulator was accepted.

### Omnipod Accepted same limits
When I deleted the simulator and added Omnipod DASH, the Max Bolus/Basal values remained too big for Omnipod. 

There should be some range checking when Omnipod is paired - the values are not saved to the pods because pods have no such concept, but the limits should be respected.

### Medtronic works as expected
I then attempted to pair a Medtronic and got - max settings exceeded.
After changing the max values to 2 and 2 and pairing pump

* attempted maxBolus of 35 (this pump allows up to 25).
* No error message is presented to the user, but the value reverted to the original 2U that was there before.
* Seems like the error shown in the Xcode log should get picked up and reported:
```
2024-06-20 14:06:17.349292-0700 FreeAPS[14404:7137695] [MinimedPumpManager] Save delivery limit settings failed: command(MinimedKit.PumpOpsError.pumpError(Max setting exceeded))
```

* same comment for maxBasal - I attempted 35, which was accepted by this pump and then 70. The attempt at 70 was restored on the display to 35 (no error was reported - same message as above).

Tagging @avouspierre and @bastiaanv for review.

pr-support_dana_simulator

### CODE REVIEW

**Review by bastiaanv — COMMENTED** [review]
LGTM! (Approved, but don't have rights to approve :) )

**Comment by marionbarker** [comment]
## Status
Confirmed Omnipods have appropriate behavior
Change from draft to final, ready for approvals.

* Note - with this change the maxBolus and maxBasal can exceed Pod capabilities, but pumpManager limits requests to allowed values.
* It would be better to limit these values to the pump values but that is outside the scope of this PR

### Details

I returned to test this with an Omnipod rPi DASH pod.
Set pump limits to DanaKit max:
* maxBasal = 35 U/hr
* maxBolus = 80 U

Attempt to set Omnipod basal rate to 35 U/hr.
* pump manager only goes up to 30 U/hr

Attempt to bolus 35 U:
* It silently limited the bolus to 30 U.
* Silent because the maxBolus was set higher than pumpManager allows

From rPi:
```
command; 0x1a; PROGRAM_INSULIN; HEX, 170e9b71101f1a0e494e532e02015a01258002580258170dc0177000030d400000000000008092 
response 0x1d; HEX, 170e9b71140a1d6802092258002f17ff0000 
```

Parsed HEX command:
```
  msgType =   0x1a17
  msgMeaning =   SetBolus
  autoBolus =   False
  prompt_bolus_u =   30.0
  nonce =   0x494e532e
  TableNum =   2
  chsum =   346
  hhEntries =   1
  secsX8Left =   9600
  pulsesPerHhr =   600
  pulse0 =   600
  xtype =   23
  xlen =   13
  reminders =   192
  promptTenthPulses =   6000
  promptDelay =   200000
  extendedTenthPulses =   0
  extendedDelay =   0
  mlen =   14
  msg_body =   1a0e494e532e02015a01258002580258170dc0177000030d40000000000000
  seqNum =   4
  rawHex =   170e9b71101f1a0e494e532e02015a01258002580258170dc0177000030d400000000000008092
  CRC =   0x8092
```

**Review by dnzxy — APPROVED** [review]

**Comment by dnzxy** [comment]
What’s the status on this PR?

**Comment by bastiaanv** [comment]
It is ready to be merged

**Review by dnzxy — APPROVED** [review]

**Review by bastiaanv — APPROVED** [review]

**Review by bastiaanv — APPROVED** [review]

**Comment by Sjoerd-Bo3** [comment]
LGTM

**Review by Sjoerd-Bo3 — APPROVED** [review]

**Pull request merged**
