### PR TITLE
Resolve issue #289: implement NS-provided display of fat/protein

### LINKED ISSUE #289: Make use of Nightscout's provided display of Carbs + Protein + Fat in graph for meal entries
## Is your feature request related to a problem? Please describe.
*Nightscout provides functionality to display carbs, protein, fat in it's main graph display. Trio has not implemented this. A very simple PR to address this is possible. This is useful for anyone who references carb/fat/protein entries in Nightscout for diabetes management.*

## Describe the solution you'd like
*A very simple PR to add "fatInput" and "proteinInput" alongside the existing "carbInput". Note that this is partially implemented, with fat and protein set to nil. This solution just finishes that half-baked implementation to bring it home!*

## Describe alternatives you've considered
*Writing custom code, or not doing this at all. Any new code would be unnecessary and would add complexity. Making use of the existing implementation is very straight-forward and follows the same pattern used for carbs. Not doing this would be silly, as it provides value for anyone who enters fat and protein in Trio (great feature with fat/protein conversion functionality!).*

## Additional context
*
image
Note - Nightscout renders protein before fat. I think most apps/systems in the DIY space tend to show fat before protein (Carbs / Fat / Protein). This rendering is part of Nightscout's implementation, and out of scope of what Trip controls.*

## Technical Details
*This implements existing code within Trio that simply set fat and protein to = nil. All we will be doing in the PR Needed here is passing along the already existing values for fat and protein, so that Trio sends them to Nightscout alongside Carbs.*

## User Impact
*Any person who uses Trio with fat and protein entries, and who uses Nightscout to review entries will benefit from this.*

### PR DESCRIPTION
**Pull request by aug0211**
- Resolves #289
- Implements Nightscout's provided graph display for fat and protein in meal entries
- Trio had partially implemented this but did not pass fat and protein values to Nightscout (it dropped them but carried carbs)
- This PR follows the identical pattern used for carbs and carries fat and protein values along for NS to display

### CODE REVIEW

**Review by MikePlante1 — APPROVED** [review]
Code review looks straightforward and clean.

Tested by making two entries and then checking Nightscout

| Entry 1 | Entry 2 |
| --- | --- |
| entry1 | entry2 |
***
Nightscout:
nightscout
***
Nightscout Report:
nightscout-report

**Review by dnzxy — APPROVED** [review]
Clean and precise changes; uses given pattern and just adds the missing data to request. 

LGTM.

**Comment by bjornoleh** [comment]
Looks good! Merging with two approvals.

**Review by dsnallfot — COMMENTED** [review]
Late to the party. But also tested. Works as described. Nice extra info to have in NS. Well done

**Review by marionbarker — COMMENTED** [review]
this is a test - can I review a closed PR?

**Comment by aug0211** [comment]
Been open too long, no movement or discussion, closing this.

**Pull request merged**
