### PR TITLE
Modify .gitmodules to point to loopandlearn organization

### PR DESCRIPTION
**Pull request by marionbarker**
### Summary 

This PR modifies the `.gitmodules` file to point to the loopandlearn github username as the source for Trio submodules.
* This enables Trio to have slight differences in submodule code with respect to LoopKit while maintaining connection to the LoopKit primary respositories
* This enables Trio developers to provide translations in the submodule repositories under loopandlearn if the ones at LoopKit are not being updated

### Rationale

Trio uses submodules based on those used by the Loop app, located at GitHub LoopKit
* There is a need to update these submodules for
   *  bug fixes
   * differences in desired default behavior
   * translation updates
* There are no Trio developers who can merge changes in LoopKit for most repositories
   * This is currently causing a roadblock for code changes and translations
* This PR changes the source for these submodules to be the GitHub loopandlearn organization
   * By using a fork of the LoopKit repositories with a specific `trio` branch, updates that are merged into LoopKit can be captured easily in the loopandlearn forks
   * Trio developers will be added to the loopandlearn organization repositories

### State before the PR

This PR is designed to only change the `.gitmodules` file and not to change any SHA.
These are the SHA for each module prior to this PR

| SHA on 13 June 2024 |	repository	| comment |
|:--|:--|:--|
|a92e9752994e7b143cdb007d3c7bcba0c0cc9214	|CGMBLEKit	|(v3.1-166-ga92e975)|
|b5e992e211d2ac6224acb105dd97fb484767da72	|G7SensorKit	|(heads/main)|
|c01eba63e94e9f6f2841a8835680c4e39c61b18d	|LibreTransmitter	|(heads/main)|
|2f535b3ca46825e82e0dd1b5ef9daccd53a3f0ca	|LoopKit	|(v3.0-1039-g2f535b3)|
|4a6df31192cbbddf62ed36ad78b1ca29649bd851	|MinimedKit	|(heads/main-6-g4a6df31)|
|85fc3c6d4805d580acdf6592b220717b6e842558	|OmniBLE	|(heads/dev)|
|a80e38b1b7f203014b461f8aff8cead2c067e39d	|OmniKit	|(heads/main)|
|a0e419da314d0ad42b41ccb04af73cd1fbf41257	|RileyLinkKit	|(heads/dev)|
|a2ccad72a55600c28549ab86ab1964c0d6558868	|TidepoolService	|(heads/dev-3-ga2ccad7)|
|21d8657d727f26df76342188e580022bf4884714	|dexcom-share-client-swift	|(v0.4.1-156-g21d8657)|

### Other information

Information used while preparing this PR are stored in this sheet: [Submodules for Trio](https://docs.google.com/spreadsheets/d/1tHxg_dwKU2NBjkr3WrLF5kLmLT0OWSw0i8gmd5nf4tA/edit?usp=sharing)
The sheet should be visible to anyone with a link.

### CODE REVIEW

**Comment by marionbarker** [comment]
### Test:
create a manual clone from the source for this PR:

```
git clone --branch=modify_submodule_source --recurse-submodules https://github.com/loopandlearn/Trio.git
```

There is one extra file (other than .gitmodules) that appears with ` git diff alpha modify_submodule_source --name-status` after cloning from loopandlearn:modify_submodule_source. I confirmed the diff is because a PR was merged into alpha after I made my feature branch and the diffs are as expected.
M       .gitmodules
M       FreeAPS/Sources/Modules/Stat/View/ChartsView.swift

Ensure the SHA for all submodules are unchanged.
Ensure that the clone builds.
Ensure no extraneous files get modified by Xcode.

**Review by bjornoleh — APPROVED** [review]
- Merged PR into alpha locally. No code changes in the merge except for .gitmodules.
- `git submodule` is identical to alpha
- Builds and runs succesfully
- No uncommitted changes after building.

A fresh clone will work the same, but did not test this.

**Review by aug0211 — APPROVED** [review]
Approved. Discussed direction in plan in admins and aligned to this path. Thanks for putting this together and hosting in LnL, Marion!

**Comment by bjornoleh** [comment]
Merging this with two approving reviews and general consensus among admins.

**Pull request merged**
